PersonalPortfolio/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonalPortfolio.Models;

namespace PersonalPortfolio.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BlogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Blogs
        public IActionResult Index()
        {
            return View( _context.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = _context.Blogs.Include(c => c.Comments)
                .FirstOrDefault(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("BlogId,Title,Author,Content")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = _context.Blogs.FirstOrDefault(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("BlogId,Title,Author,Content")] Blog blog)
        {
            if (id != blog.BlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog =  _context.Blogs
                .FirstOrDefault(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View("Delete", blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(m => m.BlogId == id);
            _context.Blogs.Remove(blog);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.BlogId == id);
        }

        public IActionResult Comments(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(m => m.BlogId == id);
            return PartialView(blog);
        }


    }
}

PersonalPortfolio/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalPortfolio</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href='~/css/site.css' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        $('.display-view').click(function () {
            let blogId = $(this).attr("name");
            $.ajax({
                type: 'GET',
                data: { id : blogId },
                dataType: 'html',
                url: '@Url.Action("Comments", "Blogs")',
                success: function (result) {
                    $('#comments').html(result);
                }
            });
        });
    });
    </script>
</head>
<body>
    <div class="header">
        <h1 class="head">JOHNNY MAYER</h1>
        <div class="leads">
            <ul>
                <li><a href="http://www.linkedin.com/in/johncmayer" target="_blank">FULL STACK DEVELOPER</a></li> | 
                <li><a href="http://www.soundcloud.com/asphaltocean" target="_blank">SOUND DESIGNER</a></li> |
                <li><a href="/Blogs">BLOG</a></li> |
                <li><a href="Home/Projects">PROJECTS</a></li>
            </ul>
        </div>
    </div>
    <hr />
    @RenderBody()
    <br />
</body>
<br />
<footer>
    @if (!User.Identity.IsAuthenticated)
    {
        <h1>ADMIN NOT LOGGED IN.</h1>
    }
    else
    {
        @Html.ActionLink("ADMIN", "Login", "Account")
    }


</footer>